const STORAGE_KEY = "roaKeyVault";
const PREFS_KEY = "lightningHubPrefs";
const CHAT_KEY = "lightningHubChatMessages";
const ACTIVE_KEY_STORAGE = "lightningHubCurrentKey";
const ADMIN_CODE = "9047";
const GAME_LIST = Array.isArray(window.GAMES_MANIFEST) ? window.GAMES_MANIFEST : [];
const LOCKED_GAME_COUNT = 450;

const LIGHTNING_COLORS = [["Midnight Storm", "#0f172a"],["Night Navy", "#111827"],["Arctic Blue", "#5ed4ff"],["Electric Cyan", "#00e7ff"],["White Bolt", "#f8fbff"],["Volt Green", "#75ff9d"],["Ion Purple", "#b285ff"],["Solar Gold", "#ffd36b"],["Storm Pink", "#ff79c9"],["Red Alert", "#ff5f70"],["Deep Ocean", "#4aa8ff"],["Violet Arc", "#8d7dff"],["Mint Shock", "#5fffd2"],["Orange Flash", "#ff9d4d"],["Neon Lime", "#c4ff47"],["Ice Lavender", "#d4d7ff"],["Blue Steel", "#7cc0ff"],["Frostbite", "#b9f2ff"],["Laser Rose", "#ff6fb5"],["Copper Spark", "#ff9966"],["Aurora Green", "#71ffbf"],["Sky Plasma", "#6bc7ff"],["Cosmic Orchid", "#bb78ff"],["Ghost White", "#f0f7ff"],["Thunder Teal", "#58f1df"],["Royal Blue", "#5b89ff"]];
const BACKGROUND_STYLES = [["None", "none"],["Blackhole", "blackhole"],["Supercell", "supercell"],["Nebula", "nebula"],["Maelstrom", "maelstrom"],["Ion Field", "ionfield"],["Eclipse", "eclipse"],["Tempest", "tempest"]];
const FONT_CHOICES = [["Trebuchet MS", '"Trebuchet MS", "Segoe UI", sans-serif'],["Segoe UI", '"Segoe UI", Tahoma, sans-serif'],["Verdana", 'Verdana, Geneva, sans-serif'],["Tahoma", 'Tahoma, Verdana, sans-serif'],["Arial", 'Arial, Helvetica, sans-serif'],["Georgia", 'Georgia, serif'],["Times New Roman", '"Times New Roman", Times, serif'],["Palatino", 'Palatino, "Palatino Linotype", serif'],["Garamond", 'Garamond, serif'],["Book Antiqua", '"Book Antiqua", Palatino, serif'],["Courier New", '"Courier New", monospace'],["Lucida Console", '"Lucida Console", Monaco, monospace'],["Consolas", 'Consolas, "Courier New", monospace'],["Candara", 'Candara, Calibri, sans-serif'],["Calibri", 'Calibri, Candara, sans-serif'],["Cambria", 'Cambria, Georgia, serif'],["Franklin Gothic", '"Franklin Gothic Medium", Arial, sans-serif'],["Gill Sans", '"Gill Sans", "Gill Sans MT", sans-serif'],["Lucida Sans", '"Lucida Sans Unicode", "Lucida Grande", sans-serif'],["Century Gothic", '"Century Gothic", Futura, sans-serif'],["Impact", 'Impact, Haettenschweiler, sans-serif'],["Copperplate", 'Copperplate, "Copperplate Gothic Light", fantasy'],["Brush Script", '"Brush Script MT", cursive'],["Perpetua", 'Perpetua, Baskerville, serif'],["Baskerville", 'Baskerville, Georgia, serif'],["Didot", 'Didot, "Times New Roman", serif'],["Rockwell", 'Rockwell, Georgia, serif'],["Optima", 'Optima, Candara, sans-serif'],["Futura", 'Futura, "Trebuchet MS", sans-serif'],["Aptos", 'Aptos, Calibri, sans-serif'],["Corbel", 'Corbel, Candara, sans-serif'],["Constantia", 'Constantia, Georgia, serif'],["Sitka", 'Sitka Text, Georgia, serif'],["Leelawadee UI", '"Leelawadee UI", Tahoma, sans-serif'],["Malgun Gothic", '"Malgun Gothic", "Segoe UI", sans-serif'],["Yu Gothic", '"Yu Gothic", "Segoe UI", sans-serif'],["MS Gothic", '"MS Gothic", monospace'],["Monaco", 'Monaco, "Lucida Console", monospace'],["American Typewriter", '"American Typewriter", Georgia, serif'],["Avenir", 'Avenir, "Segoe UI", sans-serif'],["Bodoni MT", '"Bodoni MT", Didot, serif'],["Bell MT", '"Bell MT", Georgia, serif'],["Berlin Sans", '"Berlin Sans FB", Arial, sans-serif'],["Dubai", 'Dubai, "Segoe UI", sans-serif'],["Elephant", 'Elephant, Georgia, serif']];
const defaults = { effects: "on", backgroundEnabled: "on", background: "none", lightningColor: LIGHTNING_COLORS[2][1], backgroundColor: LIGHTNING_COLORS[0][1], buttonColor: LIGHTNING_COLORS[2][1], font: FONT_CHOICES[0][1] };
const state = { sessionKeyId: null, selectedTab: "home", selectedGame: null, gameFilter: "", chatChannel: null, chatMessages: [], prefs: { ...defaults } };
const $ = (id) => document.getElementById(id);
const els = { body: document.body, keyInput: $("keyInput"), checkKeyButton: $("checkKeyButton"), keyStatus: $("keyStatus"), userDashboard: $("userDashboard"), dashboardKeyId: $("dashboardKeyId"), dashboardStatus: $("dashboardStatus"), dashboardUses: $("dashboardUses"), useFunctionButton: $("useFunctionButton"), logoutKeyButton: $("logoutKeyButton"), openAdminButton: $("openAdminButton"), hubAdminButton: $("hubAdminButton"), adminCodeOverlay: $("adminCodeOverlay"), adminCodeInput: $("adminCodeInput"), adminCodeStatus: $("adminCodeStatus"), closeAdminCodeButton: $("closeAdminCodeButton"), unlockAdminButton: $("unlockAdminButton"), adminPanelOverlay: $("adminPanelOverlay"), closeAdminPanelButton: $("closeAdminPanelButton"), keyTypeSelect: $("keyTypeSelect"), keyLabelInput: $("keyLabelInput"), usageAmountInput: $("usageAmountInput"), generateKeyButton: $("generateKeyButton"), generatorStatus: $("generatorStatus"), activeKeyCount: $("activeKeyCount"), totalKeyCount: $("totalKeyCount"), permanentKeyCount: $("permanentKeyCount"), lastGeneratedKey: $("lastGeneratedKey"), adminKeyList: $("adminKeyList"), emptyKeyState: $("emptyKeyState"), navButtons: [...document.querySelectorAll(".nav-button")], tabPanels: [...document.querySelectorAll(".tab-panel")], settingsLockedCard: $("settingsLockedCard"), settingsGrid: $("settingsGrid"), activeKeyIdTop: $("activeKeyIdTop"), activeUsesTop: $("activeUsesTop"), homeKeyValue: $("homeKeyValue"), homeUsesValue: $("homeUsesValue"), gameCountValue: $("gameCountValue"), heroPlayStrike: $("heroPlayStrike"), screenFlash: $("screenFlash"), shakeTarget: $("shakeTarget"), gameSearchInput: $("gameSearchInput"), clearGameSearchButton: $("clearGameSearchButton"), visibleGameCount: $("visibleGameCount"), totalGameCount: $("totalGameCount"), gameList: $("gameList"), selectedGameTitle: $("selectedGameTitle"), selectedGameFile: $("selectedGameFile"), openGameWindowLink: $("openGameWindowLink"), fullscreenGameButton: $("fullscreenGameButton"), gameFrame: $("gameFrame"), effectsOnButton: $("effectsOnButton"), effectsOffButton: $("effectsOffButton"), backgroundOnButton: $("backgroundOnButton"), backgroundOffButton: $("backgroundOffButton"), lightningColorSelect: $("lightningColorSelect"), backgroundColorSelect: $("backgroundColorSelect"), buttonColorSelect: $("buttonColorSelect"), backgroundStyleSelect: $("backgroundStyleSelect"), fontSelect: $("fontSelect"), chatNameInput: $("chatNameInput"), chatMessageInput: $("chatMessageInput"), sendChatButton: $("sendChatButton"), chatStatus: $("chatStatus"), chatMessages: $("chatMessages"), chatEmptyState: $("chatEmptyState"), hubUseFunctionButton: $("hubUseFunctionButton"), hubLogoutButton: $("hubLogoutButton") };
function setStatus(el, message, type = "") { el.textContent = message; el.className = "status" + (type ? " " + type : ""); }
function loadKeys() { try { const raw = localStorage.getItem(STORAGE_KEY); const parsed = raw ? JSON.parse(raw) : []; return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function saveKeys(keys) { localStorage.setItem(STORAGE_KEY, JSON.stringify(keys)); }
function generateSegment(length) { const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"; let out = ""; for (let i = 0; i < length; i += 1) out += alphabet[Math.floor(Math.random() * alphabet.length)]; return out; }
function createKeyValue(existing) { let value = ""; do { value = "RoaKey-" + generateSegment(9); } while (existing.some((x) => x.value === value)); return value; }
function createKeyId(existing) { let id = ""; do { id = "KEY-" + generateSegment(6).toUpperCase(); } while (existing.some((x) => x.id === id)); return id; }
function getKeyByValue(value) { return loadKeys().find((item) => item.value === value.trim()) || null; }
function getKeyById(id) { return loadKeys().find((item) => item.id === id) || null; }
function loadPrefs() { try { const raw = localStorage.getItem(PREFS_KEY); state.prefs = { ...defaults, ...(raw ? JSON.parse(raw) : {}) }; } catch { state.prefs = { ...defaults }; } }
function savePrefs() { localStorage.setItem(PREFS_KEY, JSON.stringify(state.prefs)); }
function populateSelect(select, items) { items.forEach(([label, value]) => { const option = document.createElement("option"); option.textContent = label; option.value = value; select.appendChild(option); }); }
function isPermanentKey(entry) { return !!entry && entry.type === "permanent"; }
function displayUses(entry) { return isPermanentKey(entry) ? "Unlimited" : String(entry.remainingUses ?? 0); }
function getKeyTypeLabel(entry) { return isPermanentKey(entry) ? "Permanent Key" : "Limited Key"; }
function currentSessionEntry() { return state.sessionKeyId ? getKeyById(state.sessionKeyId) : null; }
function updateSettingsAccess() { const permanent = isPermanentKey(currentSessionEntry()); els.settingsLockedCard.style.display = permanent ? "none" : "block"; els.settingsGrid.style.display = permanent ? "grid" : "none"; }
function hexToRgb(hex) { const clean = hex.replace("#", ""); const expanded = clean.length === 3 ? clean.split("").map((char) => char + char).join("") : clean; const value = parseInt(expanded, 16); return { r: (value >> 16) & 255, g: (value >> 8) & 255, b: value & 255 }; }
function darkenHex(hex, factor) { const { r, g, b } = hexToRgb(hex); const scale = (value) => Math.max(0, Math.min(255, Math.round(value * factor))); return `rgb(${scale(r)}, ${scale(g)}, ${scale(b)})`; }
function rgbaHex(hex, alpha) { const { r, g, b } = hexToRgb(hex); return `rgba(${r}, ${g}, ${b}, ${alpha})`; }
function applyPrefs() {
  const baseDark = darkenHex(state.prefs.backgroundColor, 0.22);
  const baseMid = darkenHex(state.prefs.backgroundColor, 0.38);
  const glowStrong = rgbaHex(state.prefs.backgroundColor, 0.24);
  const glowSoft = rgbaHex(state.prefs.backgroundColor, 0.14);
  els.body.dataset.effects = state.prefs.effects;
  els.body.dataset.backgroundEnabled = state.prefs.backgroundEnabled;
  els.body.dataset.background = state.prefs.background;
  document.documentElement.style.setProperty("--bolt", state.prefs.lightningColor);
  document.documentElement.style.setProperty("--bg-accent", state.prefs.backgroundColor);
  document.documentElement.style.setProperty("--button-accent", state.prefs.buttonColor);
  document.documentElement.style.setProperty("--bg-1", baseDark);
  document.documentElement.style.setProperty("--bg-2", baseMid);
  document.documentElement.style.setProperty("--font-choice", state.prefs.font);
  els.body.style.background = `radial-gradient(circle at 8% 10%, ${glowStrong}, transparent 28%), radial-gradient(circle at 92% 18%, ${glowSoft}, transparent 26%), radial-gradient(circle at 50% 75%, ${rgbaHex(state.prefs.backgroundColor, 0.12)}, transparent 30%), linear-gradient(165deg, ${baseDark}, ${baseMid})`;
  els.lightningColorSelect.value = state.prefs.lightningColor;
  els.backgroundColorSelect.value = state.prefs.backgroundColor;
  els.buttonColorSelect.value = state.prefs.buttonColor;
  els.backgroundStyleSelect.value = state.prefs.background;
  els.fontSelect.value = state.prefs.font;
}
function updateHubSessionUI(entry) { if (!entry) { els.activeKeyIdTop.textContent = "-"; els.activeUsesTop.textContent = "0"; els.homeKeyValue.textContent = "-"; els.homeUsesValue.textContent = "0"; updateSettingsAccess(); return; } els.activeKeyIdTop.textContent = entry.id; els.activeUsesTop.textContent = displayUses(entry); els.homeKeyValue.textContent = entry.value; els.homeUsesValue.textContent = displayUses(entry); updateSettingsAccess(); }
function updateDashboardFromSession() { if (!state.sessionKeyId) { els.userDashboard.classList.remove("visible"); updateSettingsAccess(); return; } const entry = getKeyById(state.sessionKeyId); if (!entry) { state.sessionKeyId = null; localStorage.removeItem(ACTIVE_KEY_STORAGE); els.userDashboard.classList.remove("visible"); updateSettingsAccess(); return; } els.dashboardKeyId.textContent = entry.id; els.dashboardStatus.textContent = entry.active ? (isPermanentKey(entry) ? "Permanent" : "Active") : "Inactive"; els.dashboardUses.textContent = displayUses(entry); els.userDashboard.classList.add("visible"); updateHubSessionUI(entry); }
function renderKeyList() { const keys = loadKeys(); els.adminKeyList.innerHTML = ""; els.emptyKeyState.style.display = keys.length ? "none" : "block"; els.totalKeyCount.textContent = String(keys.length); els.activeKeyCount.textContent = String(keys.filter((k) => k.active).length); els.permanentKeyCount.textContent = String(keys.filter((k) => k.type === "permanent").length); keys.slice().reverse().forEach((entry) => { const card = document.createElement("article"); card.className = "admin-key-card"; const left = document.createElement("div"); left.innerHTML = `<h3 class="mono">${entry.value}</h3><p class="muted-copy">${entry.label || "No label"}</p><div class="meta-row"><span class="pill">ID: <span class="mono">${entry.id}</span></span><span class="pill">Type: ${isPermanentKey(entry) ? "Permanent" : "Limited"}</span><span class="pill">Uses Left: ${displayUses(entry)}</span><span class="pill">Status: ${entry.active ? "Active" : "Inactive"}</span></div>`; const right = document.createElement("div"); right.className = "actions"; const toggle = document.createElement("button"); toggle.type = "button"; toggle.className = "btn " + (entry.active ? "danger" : "success"); toggle.textContent = entry.active ? "Deactivate" : "Activate"; toggle.addEventListener("click", () => { const keysNow = loadKeys(); const match = keysNow.find((x) => x.id === entry.id); if (!match) return; match.active = !match.active; saveKeys(keysNow); renderKeyList(); updateDashboardFromSession(); }); right.appendChild(toggle); card.append(left, right); els.adminKeyList.appendChild(card); }); }
function openOverlay(overlay) { overlay.classList.add("visible"); }
function closeOverlay(overlay) { overlay.classList.remove("visible"); }
function playStormSequence() { if (state.prefs.effects === "off") return; els.screenFlash.classList.remove("active"); els.shakeTarget.classList.remove("shake"); void els.screenFlash.offsetWidth; els.screenFlash.classList.add("active"); els.shakeTarget.classList.add("shake"); setTimeout(() => els.shakeTarget.classList.remove("shake"), 900); setTimeout(() => els.screenFlash.classList.remove("active"), 520); }
function activateHub() { els.body.classList.remove("mode-locked"); els.body.classList.add("mode-hub"); selectTab(state.selectedTab); playStormSequence(); }
function selectTab(tabName) { state.selectedTab = tabName; els.navButtons.forEach((button) => button.classList.toggle("active", button.dataset.tab === tabName)); els.tabPanels.forEach((panel) => panel.classList.toggle("active", panel.id === `tab-${tabName}`)); }
function consumeOneFunction(openHub = false) { if (!state.sessionKeyId) { setStatus(els.keyStatus, "No active key session.", "error"); return false; } const keys = loadKeys(); const entry = keys.find((item) => item.id === state.sessionKeyId); if (!entry) { setStatus(els.keyStatus, "Active session key is missing.", "error"); return false; } if (!entry.active) { setStatus(els.keyStatus, "This key is inactive.", "error"); return false; } if (!isPermanentKey(entry) && entry.remainingUses <= 0) { setStatus(els.keyStatus, "No functions left on this key.", "error"); return false; } if (!isPermanentKey(entry)) entry.remainingUses -= 1; saveKeys(keys); localStorage.setItem(ACTIVE_KEY_STORAGE, entry.id); renderKeyList(); updateDashboardFromSession(); setStatus(els.keyStatus, isPermanentKey(entry) ? "Permanent key used. Unlimited access remains active." : entry.remainingUses <= 0 ? "This key just reached zero functions left." : "One function was used. Remaining amount updated.", isPermanentKey(entry) ? "ok" : entry.remainingUses <= 0 ? "warn" : "ok"); if (openHub) activateHub(); return true; }
function sanitizeGameTitle(title) { return title.replace(/\s+-\s+TopVAZ$/i, "").trim(); }
function normalizeGameSrc(src) {
  if (!src) return "";
  if (/^https?:\/\//i.test(src)) return src;
  return encodeURI(src);
}
function isLockedGame(item) {
  const index = GAME_LIST.findIndex((game) => game.file === item.file);
  return index > -1 && index < LOCKED_GAME_COUNT;
}
function canAccessGame(item) {
  return !isLockedGame(item) || isPermanentKey(currentSessionEntry());
}
function selectGame(item, rerender = true) {
  state.selectedGame = item;
  if (!canAccessGame(item)) {
    els.selectedGameTitle.textContent = sanitizeGameTitle(item.title);
    els.selectedGameFile.textContent = "Permanent key required";
    els.openGameWindowLink.href = "#";
    els.gameFrame.srcdoc = "<!DOCTYPE html><html><body style='margin:0;display:grid;place-items:center;min-height:100vh;background:#07111f;color:#edf4ff;font-family:Segoe UI,sans-serif;'><div style='text-align:center;padding:2rem;max-width:42rem;'><h2 style='margin:0 0 1rem;'>Game Locked</h2><p style='margin:0;color:#9fb5d4;line-height:1.7;'>This game is part of the permanent-key collection. Unlock it with a permanent key to play it in the iframe.</p></div></body></html>";
    if (rerender) renderGames();
    return;
  }
  const directSrc = normalizeGameSrc(item.gameSrc);
  const fallbackPath = encodeURI(item.file);
  const playerSrc = directSrc || fallbackPath;
  els.selectedGameTitle.textContent = sanitizeGameTitle(item.title);
  els.selectedGameFile.textContent = playerSrc;
  els.openGameWindowLink.href = playerSrc;
  els.gameFrame.removeAttribute("srcdoc");
  els.gameFrame.onload = null;
  els.gameFrame.src = playerSrc;
  if (rerender) renderGames();
}
function fullscreenGame() {
  const frame = els.gameFrame;
  if (frame.requestFullscreen) return frame.requestFullscreen();
  if (frame.webkitRequestFullscreen) return frame.webkitRequestFullscreen();
  if (frame.msRequestFullscreen) return frame.msRequestFullscreen();
}
function renderGames() { const query = state.gameFilter.trim().toLowerCase(); const games = GAME_LIST.filter((item) => !query || sanitizeGameTitle(item.title).toLowerCase().includes(query) || item.file.toLowerCase().includes(query)); els.gameList.innerHTML = ""; els.visibleGameCount.textContent = String(games.length); els.totalGameCount.textContent = String(GAME_LIST.length); els.gameCountValue.textContent = String(GAME_LIST.length); games.forEach((item) => { const locked = isLockedGame(item); const accessible = canAccessGame(item); const button = document.createElement("button"); button.type = "button"; button.className = "game-item" + (state.selectedGame && state.selectedGame.file === item.file ? " active" : "") + (locked ? " game-item-locked" : ""); button.innerHTML = `<h4>${sanitizeGameTitle(item.title)}</h4><small class="mono">${item.file}</small>${locked ? `<small>${accessible ? "Permanent collection" : "Locked: permanent key"}</small>` : ""}`; button.addEventListener("click", () => selectGame(item)); els.gameList.appendChild(button); }); if (!games.length) { const empty = document.createElement("div"); empty.className = "empty-state"; empty.textContent = "No games match your search."; els.gameList.appendChild(empty); } if (!state.selectedGame && GAME_LIST.length) selectGame(GAME_LIST[0], false); }
function normalizeText(input) { return input.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[0]/g, "o").replace(/[1!|]/g, "i").replace(/[3]/g, "e").replace(/[4@]/g, "a").replace(/[5$]/g, "s").replace(/[7]/g, "t").replace(/[8]/g, "b").replace(/[^a-z\s]/g, "").replace(/(.)\1{2,}/g, "$1").replace(/\s+/g, " ").trim(); }
const bannedPatterns = ["nigger", "nigga", "niga", "niger", "chink", "spic", "kike", "gook", "wetback", "faggot", "tranny", "raghead", "coon", "paki", "beaner"];
function containsBlockedLanguage(message) { const normalized = normalizeText(message).replace(/\s/g, ""); return bannedPatterns.some((term) => normalized.includes(term)); }
function containsImageAttempt(message) { const text = message.toLowerCase(); return /<img|!\[.*?\]\(.*?\)|data:image|\bhttps?:\/\/\S+\.(png|jpg|jpeg|gif|webp|bmp|svg)\b/.test(text); }
function loadChatMessages() { try { const raw = localStorage.getItem(CHAT_KEY); const parsed = raw ? JSON.parse(raw) : []; state.chatMessages = Array.isArray(parsed) ? parsed.slice(-150) : []; } catch { state.chatMessages = []; } }
function saveChatMessages() { localStorage.setItem(CHAT_KEY, JSON.stringify(state.chatMessages.slice(-150))); }
function renderChat() { els.chatMessages.innerHTML = ""; els.chatEmptyState.style.display = state.chatMessages.length ? "none" : "block"; state.chatMessages.forEach((message) => { const item = document.createElement("article"); item.className = "message-item"; const head = document.createElement("div"); head.className = "message-head"; const nameWrap = document.createElement("div"); nameWrap.className = "message-name-wrap"; const name = document.createElement("div"); name.className = "message-name"; name.textContent = message.name; const badge = document.createElement("span"); badge.className = "chat-key-badge " + (message.keyType === "permanent" ? "chat-key-permanent" : "chat-key-limited"); badge.textContent = message.keyType === "permanent" ? "$ Permanent Key" : "Limited Key"; nameWrap.append(name, badge); const time = document.createElement("div"); time.className = "message-time"; time.textContent = new Date(message.time).toLocaleString(); const body = document.createElement("div"); body.className = "message-body"; body.textContent = message.text; head.append(nameWrap, time); item.append(head, body); els.chatMessages.appendChild(item); }); els.chatMessages.scrollTop = els.chatMessages.scrollHeight; }
function addChatMessage(name, text, entry) { state.chatMessages.push({ id: "msg-" + Date.now(), name, text, time: new Date().toISOString(), keyType: isPermanentKey(entry) ? "permanent" : "limited" }); state.chatMessages = state.chatMessages.slice(-150); saveChatMessages(); renderChat(); if (state.chatChannel) state.chatChannel.postMessage({ type: "sync" }); }
function initChatSync() { loadChatMessages(); renderChat(); if ("BroadcastChannel" in window) { state.chatChannel = new BroadcastChannel("lightning-hub-chat"); state.chatChannel.addEventListener("message", () => { loadChatMessages(); renderChat(); }); } window.addEventListener("storage", (event) => { if (event.key === CHAT_KEY) { loadChatMessages(); renderChat(); } }); }
function handleSendChat() { const name = els.chatNameInput.value.trim() || "Anonymous"; const text = els.chatMessageInput.value.trim(); const entry = currentSessionEntry(); if (!entry) return setStatus(els.chatStatus, "You need an active key session to chat.", "error"); if (!text) return setStatus(els.chatStatus, "Write a message first.", "error"); if (containsImageAttempt(text)) return setStatus(els.chatStatus, "Photos and image links are not allowed in chat.", "error"); if (containsBlockedLanguage(text)) return setStatus(els.chatStatus, "That message was blocked because it looks like hateful or slur-based language.", "error"); if (name.length > 24) return setStatus(els.chatStatus, "Display name is too long.", "error"); if (!consumeOneFunction(false)) return setStatus(els.chatStatus, "You need 1 function available to send a chat message.", "error"); addChatMessage(name, text, entry); els.chatMessageInput.value = ""; setStatus(els.chatStatus, isPermanentKey(entry) ? "Message sent with permanent key access." : "Message sent. 1 function used.", "ok"); }
function seedFromSavedSession() { const saved = localStorage.getItem(ACTIVE_KEY_STORAGE); if (!saved) return; const entry = getKeyById(saved); if (entry && entry.active && (isPermanentKey(entry) || entry.remainingUses > 0)) { state.sessionKeyId = entry.id; updateDashboardFromSession(); } else localStorage.removeItem(ACTIVE_KEY_STORAGE); }

els.checkKeyButton.addEventListener("click", () => { const value = els.keyInput.value.trim(); if (!value) return setStatus(els.keyStatus, "Enter a key first.", "error"); const entry = getKeyByValue(value); if (!entry) return setStatus(els.keyStatus, "Key not found.", "error"); if (!entry.active) return setStatus(els.keyStatus, "This key is inactive.", "error"); if (!isPermanentKey(entry) && entry.remainingUses <= 0) return setStatus(els.keyStatus, "This key has no functions left.", "error"); state.sessionKeyId = entry.id; localStorage.setItem(ACTIVE_KEY_STORAGE, entry.id); setStatus(els.keyStatus, "Key accepted. Use your function to open Lightning Hub.", "ok"); updateDashboardFromSession(); });
els.keyInput.addEventListener("keydown", (event) => { if (event.key === "Enter") { event.preventDefault(); els.checkKeyButton.click(); } });
els.useFunctionButton.addEventListener("click", () => consumeOneFunction(true));
els.hubUseFunctionButton.addEventListener("click", () => { if (consumeOneFunction()) playStormSequence(); });
function logoutSession() { state.sessionKeyId = null; localStorage.removeItem(ACTIVE_KEY_STORAGE); els.userDashboard.classList.remove("visible"); els.keyInput.value = ""; els.body.classList.remove("mode-hub"); els.body.classList.add("mode-locked"); updateHubSessionUI(null); setStatus(els.keyStatus, "Session closed."); }
els.logoutKeyButton.addEventListener("click", logoutSession); els.hubLogoutButton.addEventListener("click", logoutSession);
function openAdminAccess() { els.adminCodeInput.value = ""; setStatus(els.adminCodeStatus, "Enter the admin code to continue."); openOverlay(els.adminCodeOverlay); }
els.openAdminButton.addEventListener("click", openAdminAccess); els.hubAdminButton.addEventListener("click", openAdminAccess); els.closeAdminCodeButton.addEventListener("click", () => closeOverlay(els.adminCodeOverlay)); els.closeAdminPanelButton.addEventListener("click", () => closeOverlay(els.adminPanelOverlay));
els.unlockAdminButton.addEventListener("click", () => { if (els.adminCodeInput.value === ADMIN_CODE) { closeOverlay(els.adminCodeOverlay); openOverlay(els.adminPanelOverlay); renderKeyList(); setStatus(els.generatorStatus, "Generator unlocked.", "ok"); } else setStatus(els.adminCodeStatus, "Incorrect admin code.", "error"); });
els.adminCodeInput.addEventListener("keydown", (event) => { if (event.key === "Enter") { event.preventDefault(); els.unlockAdminButton.click(); } });
els.generateKeyButton.addEventListener("click", () => { const usageValue = Number(els.usageAmountInput.value); const keyType = els.keyTypeSelect.value; if (keyType !== "permanent" && (!Number.isInteger(usageValue) || usageValue <= 0)) return setStatus(els.generatorStatus, "Usage amount must be a whole number above 0 for limited keys.", "error"); const keys = loadKeys(); const newKey = { id: createKeyId(keys), value: keyType === "permanent" ? `RoaPermanent-${generateSegment(8)}` : createKeyValue(keys), label: els.keyLabelInput.value.trim(), remainingUses: keyType === "permanent" ? null : usageValue, active: true, type: keyType, createdAt: new Date().toISOString() }; while (keys.some((x) => x.value === newKey.value)) newKey.value = keyType === "permanent" ? `RoaPermanent-${generateSegment(8)}` : createKeyValue(keys); keys.push(newKey); saveKeys(keys); els.lastGeneratedKey.textContent = newKey.value; els.keyLabelInput.value = ""; setStatus(els.generatorStatus, keyType === "permanent" ? `Permanent key generated: ${newKey.value}.` : `New key generated: ${newKey.value} with ${usageValue} functions.`, "ok"); renderKeyList(); });
[els.adminCodeOverlay, els.adminPanelOverlay].forEach((overlay) => overlay.addEventListener("click", (event) => { if (event.target === overlay) closeOverlay(overlay); }));
els.navButtons.forEach((button) => button.addEventListener("click", () => selectTab(button.dataset.tab)));
els.heroPlayStrike.addEventListener("click", playStormSequence);
els.fullscreenGameButton.addEventListener("click", fullscreenGame);
els.gameSearchInput.addEventListener("input", () => { state.gameFilter = els.gameSearchInput.value; renderGames(); });
els.clearGameSearchButton.addEventListener("click", () => { els.gameSearchInput.value = ""; state.gameFilter = ""; renderGames(); });
els.effectsOnButton.addEventListener("click", () => { state.prefs.effects = "on"; savePrefs(); applyPrefs(); playStormSequence(); });
els.effectsOffButton.addEventListener("click", () => { state.prefs.effects = "off"; savePrefs(); applyPrefs(); });
els.backgroundOnButton.addEventListener("click", () => { state.prefs.backgroundEnabled = "on"; savePrefs(); applyPrefs(); });
els.backgroundOffButton.addEventListener("click", () => { state.prefs.backgroundEnabled = "off"; savePrefs(); applyPrefs(); });
els.lightningColorSelect.addEventListener("change", () => { state.prefs.lightningColor = els.lightningColorSelect.value; savePrefs(); applyPrefs(); });
els.backgroundColorSelect.addEventListener("change", () => { state.prefs.backgroundColor = els.backgroundColorSelect.value; savePrefs(); applyPrefs(); });
els.buttonColorSelect.addEventListener("change", () => { state.prefs.buttonColor = els.buttonColorSelect.value; savePrefs(); applyPrefs(); });
els.backgroundStyleSelect.addEventListener("change", () => { state.prefs.background = els.backgroundStyleSelect.value; savePrefs(); applyPrefs(); });
els.fontSelect.addEventListener("change", () => { state.prefs.font = els.fontSelect.value; savePrefs(); applyPrefs(); });
els.sendChatButton.addEventListener("click", handleSendChat); els.chatMessageInput.addEventListener("keydown", (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); handleSendChat(); } });
els.keyTypeSelect.addEventListener("change", () => { const permanent = els.keyTypeSelect.value === "permanent"; els.usageAmountInput.disabled = permanent; els.usageAmountInput.value = permanent ? "" : "400"; els.usageAmountInput.placeholder = permanent ? "Unlimited" : "Usage amount"; });
function init() { populateSelect(els.lightningColorSelect, LIGHTNING_COLORS); populateSelect(els.backgroundColorSelect, LIGHTNING_COLORS); populateSelect(els.buttonColorSelect, LIGHTNING_COLORS); populateSelect(els.backgroundStyleSelect, BACKGROUND_STYLES); populateSelect(els.fontSelect, FONT_CHOICES); loadPrefs(); applyPrefs(); els.keyTypeSelect.dispatchEvent(new Event("change")); seedFromSavedSession(); renderKeyList(); renderGames(); initChatSync(); updateSettingsAccess(); els.totalGameCount.textContent = String(GAME_LIST.length); els.visibleGameCount.textContent = String(GAME_LIST.length); }
init();
